specVersion: 0.0.2
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: Factory
    network: {{network}}
    source:
      address: "{{factory.address}}"
      abi: Factory
      startBlock: {{factory.startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/factory.ts
      entities:
        - Token
        - LiquidityPool
      abis:
        - name: Factory
          file: ./abis/smardex/Factory.json
        - name: TokenABI
          file: ./abis/uniswap-v2/ERC20.json
      eventHandlers:
        - event: PairCreated(indexed address,indexed address,address,uint256)
          handler: handlePairCreated
          ##callHandlers:
          ##- function: setFeeTo(address)
          ##handler: handleFeeTo
templates:
  - kind: ethereum/contract
    name: Pair
    network: {{network}}
    source:
      abi: Pair
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/pool.ts
      entities:
        - Token
        - Deposit
        - Withdraw
        - Swap
        - LiquidityPool
        - Token
      abis:
        - name: Pair
          file: ./abis/smardex/Pair.json
        - name: Factory
          file: ./abis/smardex/Factory.json
        - name: TokenABI
          file: ./abis/uniswap-v2/ERC20.json
      eventHandlers:
        - event: Mint(indexed address,indexed address,uint256,uint256)
          handler: handleMint
        - event: Burn(indexed address,indexed address,uint256,uint256)
          handler: handleBurn
        - event: Swap(indexed address,indexed address,int256,int256)
          handler: handleSwap
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Sync(uint256,uint256,uint256,uint256,uint256,uint256)
          handler: handleSync
          