specVersion: 0.0.2
description: Bancor
repository:
schema:
  file: ./schema.graphql
dataSources:
  #  - kind: ethereum/contract
  #    name: ContractRegistryContract
  #    network: mainnet
  #    source:
  #      address: "0x52Ae12ABe5D8BD778BD5397F99cA900624CfADD4"
  #      abi: ContractRegistryContract
  #      startBlock: 6563025
  #    mapping:
  #      kind: ethereum/events
  #      apiVersion: 0.0.7
  #      language: wasm/assemblyscript
  #      entities:
  #        - AddressUpdate
  #        - OwnerUpdate
  #      abis:
  #        - name: ContractRegistryContract
  #          file: ./abis/ContractRegistryContract.json
  #      eventHandlers:
  #        - event: AddressUpdate(indexed bytes32,address)
  #          handler: handleAddressUpdate
  #        - event: OwnerUpdate(indexed address,indexed address)
  #          handler: handleContractRegistryOwnerUpdate
  #      file: ./src/mappings/contractRegistry.ts
  #      #  - kind: ethereum/contract
  #      #    name: BancorConverterRegistry
  #      #    network: mainnet
  #      #    source:
  #      #      address: "0x0DDFF327ddF7fE838e3e63d02001ef23ad1EdE8e"
  #      #      abi: BancorConverterRegistry
  #      #      startBlock: 7764526
  #      #    mapping:
  #      #      kind: ethereum/events
  #      #      apiVersion: 0.0.7
  #      #      language: wasm/assemblyscript
  #      #      entities:
  #      #        - DexAmmProtocol
  #      #      abis:
  #      #        - name: BancorConverterRegistry
  #      #          file: ./abis/BancorConverterRegistry.json
  #      #        - name: SmartToken1
  #      #          file: ./abis/SmartToken1.json
  #      #        - name: BancorConverter1
  #      #          file: ./abis/BancorConverter1.json
  #      #        - name: BancorConverter2
  #      #          file: ./abis/BancorConverter2.json
  #      #        - name: BancorConverter3
  #      #          file: ./abis/BancorConverter3.json
  #      #        - name: ConverterContractOld
  #      #          file: ./abis/ConverterContractOld.json
  #      #        - name: SmartTokenContract
  #      #          file: ./abis/SmartTokenContract.json
  #      #        - name: SmartTokenContract
  #      #          file: ./abis/SmartTokenContract.json
  #      #        - name: ERC20Contract
  #      #          file: ./abis/ERC20Contract.json
  #      #        - name: ERC20SymbolBytes
  #      #          file: ./abis/ERC20SymbolBytes.json
  #      #        - name: ERC20NameBytes
  #      #          file: ./abis/ERC20NameBytes.json
  #      #      eventHandlers:
  #      #        - event: ConverterAddition(indexed address,address)
  #      #          handler: handleConverterAddition
  #      #        - event: ConverterRemoval(indexed address,address)
  #      #          handler: handleConverterRemoval
  #      #        - event: OwnerUpdate(indexed address,indexed address)
  #      #          handler: handleConverterRegistryOwnerUpdate
  #             file: ./src/mappings/converterRegistry1.ts
  - kind: ethereum/contract
    name: ConverterRegistry1
    network: mainnet
    source:
      address: "0x3b3bf16028e40bd3a7af66ef04e41e3bf6f51e55"
      abi: ConverterRegistry1
      startBlock: 10276640
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - DexAmmProtocol
      abis:
        - name: ConverterRegistry1
          file: ./abis/ConverterRegistry1.json
        - name: SmartToken1
          file: ./abis/SmartToken1.json
        - name: ConverterBase
          file: ./abis/ConverterBase.json
        - name: ERC20Contract
          file: ./abis/ERC20Contract.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
      eventHandlers:
        - event: ConverterAnchorAdded(indexed address)
          handler: handleConverterAnchorAdded
      file: ./src/mappings/converterRegistry.ts
  - kind: ethereum/contract
    name: ConverterRegistry2
    network: mainnet
    source:
      address: "0x06915fb082d34ff4fe5105e5ff2829dc5e7c3c6d"
      abi: ConverterRegistry1
      startBlock: 10276772
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - DexAmmProtocol
      abis:
        - name: ConverterRegistry1
          file: ./abis/ConverterRegistry1.json
        - name: SmartToken1
          file: ./abis/SmartToken1.json
        - name: ConverterBase
          file: ./abis/ConverterBase.json
        - name: ERC20Contract
          file: ./abis/ERC20Contract.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
      eventHandlers:
        - event: ConverterAnchorAdded(indexed address)
          handler: handleConverterAnchorAdded
      file: ./src/mappings/converterRegistry.ts
  - kind: ethereum/contract
    name: ConverterRegistry3
    network: mainnet
    source:
      address: "0xeb53781a5a0819375d04251a615e3a039f296ca9"
      abi: ConverterRegistry3
      startBlock: 10931278
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - DexAmmProtocol
      abis:
        - name: ConverterRegistry1
          file: ./abis/ConverterRegistry1.json
        - name: ConverterRegistry3
          file: ./abis/ConverterRegistry3.json
        - name: SmartToken1
          file: ./abis/SmartToken1.json
        - name: DSToken
          file: ./abis/DSToken.json
        - name: ConverterBase
          file: ./abis/ConverterBase.json
        - name: StandardPoolConverter
          file: ./abis/StandardPoolConverter.json
        - name: ERC20Contract
          file: ./abis/ERC20Contract.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
      eventHandlers:
        - event: ConverterAnchorAdded(indexed address)
          handler: handleConverterAnchorAdded
      file: ./src/mappings/converterRegistry.ts
  - kind: ethereum/contract
    name: ConverterRegistry4
    network: mainnet
    source:
      address: "0xc0205e203f423bcd8b2a4d6f8c8a154b0aa60f19"
      abi: ConverterRegistry3
      startBlock: 11451530
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - DexAmmProtocol
      abis:
        - name: ConverterRegistry1
          file: ./abis/ConverterRegistry1.json
        - name: ConverterRegistry3
          file: ./abis/ConverterRegistry3.json
        - name: SmartToken1
          file: ./abis/SmartToken1.json
        - name: DSToken
          file: ./abis/DSToken.json
        - name: ConverterBase
          file: ./abis/ConverterBase.json
        - name: StandardPoolConverter
          file: ./abis/StandardPoolConverter.json
        - name: ERC20Contract
          file: ./abis/ERC20Contract.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
      eventHandlers:
        - event: ConverterAnchorAdded(indexed address)
          handler: handleConverterAnchorAdded
      file: ./src/mappings/converterRegistry.ts
  - kind: ethereum/contract
    name: BancorNetwork1
    network: mainnet
    source:
      address: "0x923cab01e6a4639664aa64b76396eec0ea7d3a5f"
      abi: BancorNetwork1
      startBlock: 10276626
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Swap
      abis:
        - name: BancorNetwork1
          file: ./abis/BancorNetwork1.json
        - name: ConverterRegistry1
          file: ./abis/ConverterRegistry1.json
        - name: SmartToken1
          file: ./abis/SmartToken1.json
        - name: DSToken
          file: ./abis/DSToken.json
        - name: ConverterBase
          file: ./abis/ConverterBase.json
        - name: StandardPoolConverter
          file: ./abis/StandardPoolConverter.json
        - name: ERC20Contract
          file: ./abis/ERC20Contract.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
      eventHandlers:
        - event: Conversion(indexed address,indexed address,indexed address,uint256,uint256,address)
          handler: handleBancorNetworkConversion
      file: ./src/mappings/bancorNetwork.ts
  - kind: ethereum/contract
    name: BancorNetwork2
    network: mainnet
    source:
      address: "0x5f58058c0ec971492166763c8c22632b583f667f"
      abi: BancorNetwork1
      startBlock: 10277001
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Swap
      abis:
        - name: BancorNetwork1
          file: ./abis/BancorNetwork1.json
        - name: ConverterRegistry1
          file: ./abis/ConverterRegistry1.json
        - name: SmartToken1
          file: ./abis/SmartToken1.json
        - name: DSToken
          file: ./abis/DSToken.json
        - name: ConverterBase
          file: ./abis/ConverterBase.json
        - name: StandardPoolConverter
          file: ./abis/StandardPoolConverter.json
        - name: ERC20Contract
          file: ./abis/ERC20Contract.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
      eventHandlers:
        - event: Conversion(indexed address,indexed address,indexed address,uint256,uint256,address)
          handler: handleBancorNetworkConversion
      file: ./src/mappings/bancorNetwork.ts
  - kind: ethereum/contract
    name: BancorNetwork3
    network: mainnet
    source:
      address: "0x8dfeb86c7c962577ded19ab2050ac78654fea9f7"
      abi: BancorNetwork1
      startBlock: 10282599
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Swap
      abis:
        - name: BancorNetwork1
          file: ./abis/BancorNetwork1.json
        - name: ConverterRegistry1
          file: ./abis/ConverterRegistry1.json
        - name: SmartToken1
          file: ./abis/SmartToken1.json
        - name: DSToken
          file: ./abis/DSToken.json
        - name: ConverterBase
          file: ./abis/ConverterBase.json
        - name: StandardPoolConverter
          file: ./abis/StandardPoolConverter.json
        - name: ERC20Contract
          file: ./abis/ERC20Contract.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
      eventHandlers:
        - event: Conversion(indexed address,indexed address,indexed address,uint256,uint256,address)
          handler: handleBancorNetworkConversion
      file: ./src/mappings/bancorNetwork.ts
  - kind: ethereum/contract
    name: BancorNetwork4
    network: mainnet
    source:
      address: "0x2f9ec37d6ccfff1cab21733bdadede11c823ccb0"
      abi: BancorNetwork4
      startBlock: 10287416
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Swap
      abis:
        - name: BancorNetwork1
          file: ./abis/BancorNetwork1.json
        - name: BancorNetwork4
          file: ./abis/BancorNetwork4.json
        - name: ConverterRegistry1
          file: ./abis/ConverterRegistry1.json
        - name: SmartToken1
          file: ./abis/SmartToken1.json
        - name: DSToken
          file: ./abis/DSToken.json
        - name: ConverterBase
          file: ./abis/ConverterBase.json
        - name: StandardPoolConverter
          file: ./abis/StandardPoolConverter.json
        - name: ERC20Contract
          file: ./abis/ERC20Contract.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
      eventHandlers:
        - event: Conversion(indexed address,indexed address,indexed address,uint256,uint256,address)
          handler: handleBancorNetworkConversion
      file: ./src/mappings/bancorNetwork.ts
templates:
  - kind: ethereum/contract
    name: Converter
    network: mainnet
    source:
      abi: ConverterBase
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - NewSmartToken
        - Issuance
        - Destruction
        - Transfer
        - Approval
        - OwnerUpdate
      abis:
        - name: ConverterBase
          file: ./abis/ConverterBase.json
        - name: SmartToken1
          file: ./abis/SmartToken1.json
        - name: ERC20Contract
          file: ./abis/ERC20Contract.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
      eventHandlers:
        - event: LiquidityAdded(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleLiquidityAdded
        - event: LiquidityRemoved(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleLiquidityRemoved
      #        - event: Conversion(indexed address,indexed address,indexed address,uint256,uint256,int256)
      #          handler: handleConversion
      file: ./src/mappings/converter.ts
