specVersion: 0.0.2
description: Dodo-v2.io
repository: https://github.com/DODOEX/dodoex_v2_subgraph
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: DVMFactory
    network: mainnet
    source:
      address: '0x72d220ce168c4f361dd4dee5d826a01ad8598f6c'
      abi: DVMFactory
      startBlock: 11704651
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/poolFactory.ts
      entities:
        - Pair
        - Token
      abis:
        - name: DVMFactory
          file: ./abis/dodo-v2/DVMFactory.json
        - name: ERC20
          file: ./abis/dodo-v2/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v2/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v2/ERC20NameBytes.json
        - name: DVM
          file: ./abis/dodo-v2/DVM.json
        - name: FeeRateModel
          file: ./abis/dodo-v2/FeeRateModel.json
      eventHandlers:
        - event: NewDVM(address,address,address,address)
          handler: handleNewDVM
        - event: RemoveDVM(address)
          handler: handleRemoveDVM
  - kind: ethereum/contract
    name: DPPFactory_2021_01_22
    network: mainnet
    source:
      address: "0xb5dc5e183c2acf02ab879a8569ab4edaf147d537"
      abi: DPPFactory
      startBlock: 11704659
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/poolFactory.ts
      entities:
        - Pair
        - Token
      abis:
        - name: DPPFactory
          file: ./abis/dodo-v2/DPPFactory.json
        - name: ERC20
          file: ./abis/dodo-v2/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v2/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v2/ERC20NameBytes.json
        - name: DPP
          file: ./abis/dodo-v2/DPP.json
        - name: FeeRateModel
          file: ./abis/dodo-v2/FeeRateModel.json
      eventHandlers:
        - event: NewDPP(address,address,address,address)
          handler: handleNewDPP
  - kind: ethereum/contract
    name: DPPFactory
    network: mainnet
    source:
      address: "0x6b4fa0bc61eddc928e0df9c7f01e407bfcd3e5ef"
      abi: DPPFactory
      startBlock: 11730389
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/poolFactory.ts
      entities:
        - Pair
        - Token
      abis:
        - name: DPPFactory
          file: ./abis/dodo-v2/DPPFactory.json
        - name: ERC20
          file: ./abis/dodo-v2/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v2/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v2/ERC20NameBytes.json
        - name: DPP
          file: ./abis/dodo-v2/DPP.json
        - name: FeeRateModel
          file: ./abis/dodo-v2/FeeRateModel.json
      eventHandlers:
        - event: NewDPP(address,address,address,address)
          handler: handleNewDPP
        - event: RemoveDPP(address)
          handler: handleRemoveDPP
  - kind: ethereum/contract
    name: DPPFactory_21_10_13
    network: mainnet
    source:
      address: "0x5336ede8f971339f6c0e304c66ba16f1296a2fbe"
      abi: DPPFactory
      startBlock: 13397058
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/poolFactory.ts
      entities:
        - Pair
        - Token
      abis:
        - name: DPPFactory
          file: ./abis/dodo-v2/DPPFactory.json
        - name: ERC20
          file: ./abis/dodo-v2/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v2/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v2/ERC20NameBytes.json
        - name: DPP
          file: ./abis/dodo-v2/DPP.json
        - name: FeeRateModel
          file: ./abis/dodo-v2/FeeRateModel.json
      eventHandlers:
        - event: NewDPP(address,address,address,address)
          handler: handleNewDPP
        - event: RemoveDPP(address)
          handler: handleRemoveDPP
  - kind: ethereum/contract
    name: DSPFactory
    network: mainnet
    source:
      address: '0x6fddb76c93299d985f4d3fc7ac468f9a168577a4'
      abi: DSPFactory
      startBlock: 12269078
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/poolFactory.ts
      entities:
        - Pair
        - Token
      abis:
        - name: DSPFactory
          file: ./abis/dodo-v2/DSPFactory.json
        - name: ERC20
          file: ./abis/dodo-v2/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v2/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v2/ERC20NameBytes.json
        - name: DSP
          file: ./abis/dodo-v2/DSP.json
        - name: FeeRateModel
          file: ./abis/dodo-v2/FeeRateModel.json
      eventHandlers:
        - event: NewDSP(address,address,address,address)
          handler: handleNewDSP
        - event: RemoveDSP(address)
          handler: handleRemoveDSP
  - kind: ethereum/contract
    name: CrowdPoolingFactory
    network: mainnet
    source:
      address: '0xe8c9a78725d0451fa19878d5f8a3dc0d55fecf25'
      abi: CrowdPoolingFactory
      startBlock: 11704666
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/poolFactory.ts
      entities:
        - Pair
        - Token
      abis:
        - name: DVM
          file: ./abis/dodo-v2/DVM.json
        - name: DPP
          file: ./abis/dodo-v2/DPP.json
        - name: DODO
          file: ./abis/dodo-v2/DODO.json
        - name: CrowdPoolingFactory
          file: ./abis/dodo-v2/CrowdPoolingFactory.json
        - name: ERC20
          file: ./abis/dodo-v2/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v2/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v2/ERC20NameBytes.json
        - name: CP
          file: ./abis/dodo-v2/CP.json
      eventHandlers:
        - event: NewCP(address,address,address,address)
          handler: handleNewCP
  - kind: ethereum/contract
    name: CrowdPoolingFactoryV2
    network: mainnet
    source:
      address: '0x1e5d8ee8fb7f0d791475c59391db8f6cd06aa656'
      abi: CrowdPoolingFactory
      startBlock: 13907266
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/poolFactory.ts
      entities:
        - Pair
        - Token
      abis:
        - name: DVM
          file: ./abis/dodo-v2/DVM.json
        - name: DPP
          file: ./abis/dodo-v2/DPP.json
        - name: CrowdPoolingFactory
          file: ./abis/dodo-v2/CrowdPoolingFactory.json
        - name: CrowdPoolingFactoryV2
          file: ./abis/dodo-v2/CrowdPoolingFactoryV2.json
        - name: ERC20
          file: ./abis/dodo-v2/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v2/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v2/ERC20NameBytes.json
        - name: CP
          file: ./abis/dodo-v2/CP.json
        - name: CPV2
          file: ./abis/dodo-v2/CPV2.json
      eventHandlers:
        - event: NewCP(address,address,address,address)
          handler: handleNewCP
  - kind: ethereum/contract
    name: UpCrowdPoolingFactory
    network: mainnet
    source:
      address: '0x78d338f9d54e9e41872e68cb1c01d9499d87ee52'
      abi: UpCrowdPoolingFactory
      startBlock: 12042763
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/poolFactory.ts
      entities:
        - Pair
        - Token
      abis:
        - name: DVM
          file: ./abis/dodo-v2/DVM.json
        - name: DPP
          file: ./abis/dodo-v2/DPP.json
        - name: CrowdPoolingFactory
          file: ./abis/dodo-v2/CrowdPoolingFactory.json
        - name: UpCrowdPoolingFactory
          file: ./abis/dodo-v2/UpCrowdPoolingFactory.json
        - name: ERC20
          file: ./abis/dodo-v2/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v2/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v2/ERC20NameBytes.json
        - name: CP
          file: ./abis/dodo-v2/CP.json
      eventHandlers:
        - event: NewCP(address,address,address,address)
          handler: handleNewCP
templates:
  - kind: ethereum/contract
    name: DVM
    network: mainnet
    source:
      abi: DVM
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/pool.ts
      entities:
        - Pair
        - Token
        - DODOSwap
      abis:
        - name: DVM
          file: ./abis/dodo-v2/DVM.json
        - name: DPP
          file: ./abis/dodo-v2/DPP.json
        - name: DODO
          file: ./abis/dodo-v2/DODO.json
        - name: DVMFactory
          file: ./abis/dodo-v2/DVMFactory.json
        - name: DPPFactory
          file: ./abis/dodo-v2/DPPFactory.json
        - name: FeeRateModel
          file: ./abis/dodo-v2/FeeRateModel.json
        - name: DODOZoo
          file: ./abis/dodo-v2/DODOZoo.json
      eventHandlers:
        - event: DODOSwap(address,address,uint256,uint256,address,address)
          handler: handleDODOSwap
        - event: BuyShares(address,uint256,uint256)
          handler: handleBuyShares
        - event: SellShares(address,address,uint256,uint256)
          handler: handleSellShares
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
  - kind: ethereum/contract
    name: DPP
    network: mainnet
    source:
      abi: DPP
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/pool.ts
      entities:
        - Pair
        - Token
      abis:
        - name: DVM
          file: ./abis/dodo-v2/DVM.json
        - name: DPP
          file: ./abis/dodo-v2/DPP.json
        - name: DODO
          file: ./abis/dodo-v2/DODO.json
        - name: DVMFactory
          file: ./abis/dodo-v2/DVMFactory.json
        - name: DPPFactory
          file: ./abis/dodo-v2/DPPFactory.json
        - name: ERC20
          file: ./abis/dodo-v2/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v2/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v2/ERC20NameBytes.json
        - name: FeeRateModel
          file: ./abis/dodo-v2/FeeRateModel.json
        - name: DODOZoo
          file: ./abis/dodo-v2/DODOZoo.json
      eventHandlers:
        - event: DODOSwap(address,address,uint256,uint256,address,address)
          handler: handleDODOSwap
        - event: LpFeeRateChange(uint256)
          handler: handleLpFeeRateChange
  - kind: ethereum/contract
    name: DSP
    network: mainnet
    source:
      abi: DSP
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/pool.ts
      entities:
        - Pair
        - Token
        - DODOSwap
      abis:
        - name: DVMFactory
          file: ./abis/dodo-v2/DVMFactory.json
        - name: DPPFactory
          file: ./abis/dodo-v2/DPPFactory.json
        - name: DSPFactory
          file: ./abis/dodo-v2/DSPFactory.json
        - name: DVM
          file: ./abis/dodo-v2/DVM.json
        - name: DPP
          file: ./abis/dodo-v2/DPP.json
        - name: DSP
          file: ./abis/dodo-v2/DSP.json
        - name: FeeRateModel
          file: ./abis/dodo-v2/FeeRateModel.json
        - name: DODOZoo
          file: ./abis/dodo-v2/DODOZoo.json
      eventHandlers:
        - event: DODOSwap(address,address,uint256,uint256,address,address)
          handler: handleDODOSwap
        - event: BuyShares(address,uint256,uint256)
          handler: handleBuyShares
        - event: SellShares(address,address,uint256,uint256)
          handler: handleSellShares
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
  - kind: ethereum/contract
    name: CP
    network: mainnet
    source:
      abi: CP
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/crowdPooling.ts
      entities:
        - CrowdPooling
        - Token
      abis:
        - name: DVM
          file: ./abis/dodo-v2/DVM.json
        - name: DPP
          file: ./abis/dodo-v2/DPP.json
        - name: DODO
          file: ./abis/dodo-v2/DODO.json
        - name: ERC20
          file: ./abis/dodo-v2/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v2/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v2/ERC20NameBytes.json
        - name: CP
          file: ./abis/dodo-v2/CP.json
        - name: DVMFactory
          file: ./abis/dodo-v2/DVMFactory.json
        - name: DODOZoo
          file: ./abis/dodo-v2/DODOZoo.json
      eventHandlers:
        - event: Bid(address,uint256,uint256)
          handler: handleBid
        - event: Cancel(address,uint256)
          handler: handleCancel
        - event: Settle()
          handler: handleSettle
        - event: Claim(address,uint256,uint256)
          handler: handleClaim
  - kind: ethereum/contract
    name: DODOLpToken
    network: mainnet
    source:
      abi: DODOLpToken
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/lpToken.ts
      entities:
        - Pair
        - Token
      abis:
        - name: DODOLpToken
          file: ./abis/dodo-v2/DODOLpToken.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
  - kind: ethereum/contract
    name: CPV2
    network: mainnet
    source:
      abi: CPV2
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v2/src/mappings/crowdPooling.ts
      entities:
        - CrowdPooling
        - Token
      abis:
        - name: DVM
          file: ./abis/dodo-v2/DVM.json
        - name: DPP
          file: ./abis/dodo-v2/DPP.json
        - name: ERC20
          file: ./abis/dodo-v2/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v2/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v2/ERC20NameBytes.json
        - name: CP
          file: ./abis/dodo-v2/CP.json
        - name: CPV2
          file: ./abis/dodo-v2/CPV2.json
        - name: DVMFactory
          file: ./abis/dodo-v2/DVMFactory.json
        - name: DODOZoo
          file: ./abis/dodo-v2/DODOZoo.json
      eventHandlers:
        - event: Bid(address,uint256,uint256)
          handler: handleBid
        - event: Cancel(address,uint256)
          handler: handleCancel
        - event: Settle()
          handler: handleSettle
