specVersion: 0.0.2
description: Dodo-v1.io
repository: https://github.com/DODOEX/dodoex_v2_subgraph
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: DODOZoo
    network: mainnet
    source:
      address: '0x3a97247df274a17c59a3bd12735ea3fcdfb49950'
      abi: DODOZoo
      startBlock: 10613640
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v1/src/mappings/classicPoolFromV1.ts
      entities:
        - LiquidityPool
        - Token
        - DexAmmProtocol
      abis:
        - name: DODOZoo
          file: ./abis/dodo-v1/DODOZoo.json
        - name: DVM
          file: ./abis/dodo-v1/DVM.json
        - name: DPP
          file: ./abis/dodo-v1/DPP.json
        - name: DODO
          file: ./abis/dodo-v1/DODO.json
        - name: ERC20
          file: ./abis/dodo-v1/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v1/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v1/ERC20NameBytes.json
      eventHandlers:
        - event: DODOBirth(address,address,address)
          handler: handleDODOBirth
templates:
  - kind: ethereum/contract
    name: DODO
    network: mainnet
    source:
      abi: DODO
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v1/src/mappings/classicPoolFromV1.ts
      entities:
        - Swap
        - Deposit
        - Withdraw
        - LiquidityPool
        - Token
      abis:
        - name: DVM
          file: ./abis/dodo-v1/DVM.json
        - name: DPP
          file: ./abis/dodo-v1/DPP.json
        - name: DODO
          file: ./abis/dodo-v1/DODO.json
        - name: DVMFactory
          file: ./abis/dodo-v1/DVMFactory.json
        - name: DPPFactory
          file: ./abis/dodo-v1/DPPFactory.json
        - name: DODOZoo
          file: ./abis/dodo-v1/DODOZoo.json
        - name: ERC20
          file: ./abis/dodo-v1/ERC20.json
        - name: ERC20SymbolBytes
          file: ./abis/dodo-v1/ERC20SymbolBytes.json
        - name: ERC20NameBytes
          file: ./abis/dodo-v1/ERC20NameBytes.json
      callHandlers:
        - function: disableTrading()
          handler: handleDisableTrading
        - function: enableTrading()
          handler: handleEnableTrading
        - function: disableQuoteDeposit()
          handler: handleDisableQuoteDeposit
        - function: enableQuoteDeposit()
          handler: handleEnableQuoteDeposit
        - function: disableBaseDeposit()
          handler: handleDisableBaseDeposit
        - function: enableBaseDeposit()
          handler: handleEnableBaseDeposit
      eventHandlers:
        - event: Deposit(indexed address,indexed address,bool,uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed address,bool,uint256,uint256)
          handler: handleWithdraw
        - event: SellBaseToken(indexed address,uint256,uint256)
          handler: handleSellBaseToken
        - event: BuyBaseToken(indexed address,uint256,uint256)
          handler: handleBuyBaseToken
        - event: UpdateLiquidityProviderFeeRate(uint256,uint256)
          handler: handleUpdateLiquidityProviderFeeRate
        - event: ClaimAssets(indexed address,uint256,uint256)
          handler: handleClaimAssets
        - event: ChargeMaintainerFee(indexed address,bool,uint256)
          handler: handleChargeMaintainerFee
        - event: UpdateMaintainerFeeRate(uint256,uint256)
          handler: handleUpdateMaintainerFeeRate
  - kind: ethereum/contract
    name: DODOLpToken
    network: mainnet
    source:
      abi: DODOLpToken
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./protocols/dodo-v1/src/mappings/lpToken.ts
      entities:
        - LiquidityPool
        - Token
      abis:
        - name: DODOLpToken
          file: ./abis/dodo-v1/DODOLpToken.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
